default: &default
  adapter: mysql2
  database: 'database'
  username: 'root'
  host:     <%= ENV['DATABASE_HOST'] || 'localhost' %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_520_ci
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
