default: &default
  project_name: 'Faith Spark'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  default_time_zone: <%= ENV['DEFAULT_TIME_ZONE'] || 'Central Time (US & Canada)' %>
  password_reset_host: <%= ENV['PASSWORD_RESET_HOST'] %>
  cometchat:
    app_id: <%= ENV["COMETCHAT_APP_ID"] %>
    api_key: <%= ENV["COMETCHAT_API_KEY"] %>
    debug: <%= ENV["COMETCHAT_DEBUG"] %>
    endpoint: <%= ENV["COMETCHAT_ENDPOINT"] %>
    region: <%= ENV["COMETCHAT_REGION"] %>
  email:
    from_address: <%= ENV["EMAIL_FROM"] %>
    alert_address: <%= ENV["ALERT_EMAIL"] %>
    contact_address: <%= ENV["CONTACT_EMAIL"] %>
    domain: <%= ENV["EMAIL_DOMAIN"] %>
    host: <%= ENV["EMAIL_HOST"] %>
    port: <%= ENV["EMAIL_PORT"] %>
    username: <%= ENV["EMAIL_USERNAME"] %>
    password: <%= ENV["EMAIL_PASSWORD"] %>
  firebase:
    server_key: <%= ENV["FIREBASE_SERVER_KEY"] %>
  site_url: <%= ENV["SITE_URL"] %>
  s3:
    access_key: <%= ENV["S3_ACCESS_KEY"] %>
    bucket: <%= ENV["S3_BUCKET"] %>
    hostname: <%= ENV["S3_HOSTNAME"] %>
    region: <%= ENV["S3_REGION"] %>
    secret_key: <%= ENV["S3_SECRET_KEY"] %>
  media_live:
    access_key: <%= ENV["MEDIA_LIVE_ACCESS_KEY"] %>
    account_id: <%= ENV["MEDIA_LIVE_ACCOUNT_ID"] %>
    container_id: <%= ENV["MEDIA_LIVE_CONTAINER_ID"] %>
    region: <%= ENV["MEDIA_LIVE_REGION"] %>
    secret_key: <%= ENV["MEDIA_LIVE_SECRET_KEY"] %>
    security_group_id: <%= ENV["MEDIA_LIVE_SECURITY_GROUP_ID"] %>
  training_manual_url: 'https://docs.google.com/document/d/1th7PVeQrHJUubVd4hYtqoYiPMDOZJITBuS7T5Ty2BBM/edit?usp=sharing'
  minimum_app_version_setting_name: 'Minimum App Version'
  minimum_app_version: 2.0.0
  stream_warning_duration: <%= ENV['STREAM_WARNING_DURATION']&.to_i || 120 %>
  stream_shutdown_duration: <%= ENV['STREAM_SHUTDOWN_DURATION']&.to_i || 180 %>

development:
  <<: *default
  secret_key_base: REDACTED
  cometchat:
    app_id: 175927ece42c7ab
    api_key: a39324566e83ec6593eef8b71fb1d56a171fbbcf
    debug: true
    endpoint: https://api-eu.cometchat.io/v2.0
    region: 'eu'
  email:
    from_address: 'test@example.com'
    alert_address: 'alert@example.com'
    contact_address: 'contact@example.com'
  firebase:
    server_key: REDACTED
  site_url: http://localhost:3000
  s3:
    access_key: REDACTED
    bucket: REDACTED
    hostname: s3-eu-west-1.amazonaws.com
    region: eu-west-1
    secret_key: REDACTED
  media_live:
    access_key: 'REDACTED'
    account_id: 'REDACTED'
    container_id: 'REDACTED'
    region: 'eu-west-1'
    secret_key: 'REDACTED'
    security_group_id: 'REDACTED'
  stream_warning_duration: 5
  stream_shutdown_duration: 10

test:
  <<: *default
  secret_key_base: REDACTED
  cometchat:
    app_id: COMETCHAT_APP_ID
    api_key: COMETCHAT_API_KEY
    debug: true
    endpoint: https://cometchat.test/v2.0
    region: 'eu'
  email:
    from_address: 'test@test.com'
    alert_address: 'alert@test.com'
    contact_address: 'contact@test.com'
  site_url: http://ohc.test
  media_live:
    access_key: 'xxxxx'
    account_id: 'REDACTED'
    container_id: 'REDACTED'
    region: 'eu-west-1'
    secret_key: 'xxxxxx'
    security_group_id: 'REDACTED'

production:
  <<: *default
